[command]
default=ants-launch ancil_general_regrid.py \
       =${source} -o ${output} --ants-config ${ANTS_CONFIG} --target-${target_type} ${target} \
       =${begin} ${end} --search-method ${search_method}

[env]
output=${ROSE_DATA}/${ROSE_TASK_NAME}
search_method=${CYLC_TASK_PARAM_fill}
source=${TEST_SOURCES_DIR}/ancil_general_regrid/n96e_orca_land_cover_fraction
target=${TEST_SOURCES_DIR}/ancil_general_regrid/qrparm.mask.nc
target_type=lsm
