[command]
default=ants-launch ancil_fill_n_merge.py \
       =${source} --target-lsm ${target} --polygon ${polygon} -o ${output} \
       =--ants-config ${ANTS_CONFIG} --search-method ${search_method}

[env]
polygon=${ROSE_DATA}/ite.shp
search_method=${CYLC_TASK_PARAM_fill}
source=${TEST_SOURCES_DIR}/ancil_fill_n_merge/ancil_lct_ite.nc ${TEST_SOURCES_DIR}/ancil_fill_n_merge/cci_ukv.nc
target=${TEST_SOURCES_DIR}/ancil_fill_n_merge/ukv_coarse_land_cover_fraction.nc
