[command]
default=ants-launch ancil_fill_n_merge.py \
       =${source} --target-lsm ${target} -o ${output} \
       =--ants-config ${ANTS_CONFIG} --invert-mask \
       =--search-method ${search_method} --ignore-metadata-files

[env]
search_method=${CYLC_TASK_PARAM_fill}
source=${TEST_SOURCES_DIR}/ancil_fill_n_merge/ancil_general_regrid_invert_mask_not_filled.nc
target=${TEST_SOURCES_DIR}/ancil_fill_n_merge/qrparm.mask.nc
