[env]
output=${ROSE_DATA}/${ROSE_TASK_NAME}
source=${TEST_SOURCES_DIR}/ancil_vertical_regrid/Ozone_CMIP5_SPARCex_M1994-2005_N36L85_li-ch_G.nc
target=${TEST_SOURCES_DIR}/ancil_vertical_regrid/vertlevs_L70_50t_20s_80km
target_type=grid
