[env]
filelist=ancil_fill_n_merge_land_cover_spiral
        =ancil_fill_n_merge_invert_mask_spiral
        =ancil_fill_n_merge_land_cover_kdtree
        =ancil_fill_n_merge_invert_mask_kdtree
        =ancil_fill_n_merge_land_cover_latitude_weighted_kdtree
        =ancil_fill_n_merge_invert_mask_latitude_weighted_kdtree
        =ancil_fill_n_merge_land_cover_spiral.nc
        =ancil_fill_n_merge_invert_mask_spiral.nc
        =ancil_fill_n_merge_land_cover_kdtree.nc
        =ancil_fill_n_merge_invert_mask_kdtree.nc
        =ancil_fill_n_merge_land_cover_latitude_weighted_kdtree.nc
        =ancil_fill_n_merge_invert_mask_latitude_weighted_kdtree.nc
